import { TimeOfDay, MonsterEnv, MonsterPosition } from "common.slint";



component DayAndNightImage inherits Rectangle {
    in property <image> day_image;
    in property <image> night_image;
    in property <TimeOfDay> time_of_day;
    in property <float> night_factor;

    day := Image {
        source: day_image;
        states [
            night when time_of_day == TimeOfDay.NIGHT: {
                visible: false;
            }
        ]
    }

    night_layer := Image {
        source: night_image;
        states [
            night when time_of_day == TimeOfDay.NIGHT: {
                opacity: 1.0;
            }
            twiligth when time_of_day == TimeOfDay.TWILIGHT: {
                opacity: night_factor;
            }
            day when time_of_day == TimeOfDay.DAY: {
                opacity: 0.0;
            }
        ]
    }
}

export component Monster inherits Rectangle {
    in property <bool> visible_on_screen: true;
    in property <image> img_source;
    clip: true;
    height: img.height;
    width: img.width;
    states [
        visible when visible_on_screen: {
            img.y: 0px;
        }
        not_visible when !visible_on_screen: {
            img.y: img.height;
        }
    ]
    img := Image {
        horizontal-alignment: ImageHorizontalAlignment.center;
        vertical-alignment: ImageVerticalAlignment.center;
        horizontal-tiling: ImageTiling.none;
        image-rendering: ImageRendering.pixelated;
        source: img_source;
        visible: true;
        animate y {
            easing: ease-in-out-back;
            duration: 500ms;
        }
    }
}

export component Moon inherits Rectangle {
    width: 34px;
    height: 34px;
    // border-radius: root.width / 2;
    in property <image> moon;

    // background: #fff699;

    img := Image {
        source: moon;
    }
}

export component World inherits Rectangle {

    border-radius: root.height / 2;
    clip: true;

    in property <TimeOfDay> time_of_day;
    in property <float> night_factor;
    in property <MonsterPosition> position;
    in property <image> moon;
    in property <brush> sky_brush;

    in property <image> monster;

    states [
        house when position.env == MonsterEnv.HOUSE: {
            monster_in_house.visible: true;
            monster_outside.visible: false;
        }
        outside when position.env == MonsterEnv.OUTSIDE: {
            monster_in_house.visible: false;
            monster_outside.visible: true;
        }
    ]

    sky := Rectangle {
        border-radius: root.width / 2;
        height: 100%;
        width: 100%;
        // background: @linear-gradient(90deg, #b54910.darker(angle / 100)  10%,  #214050.darker(angle / 100) 90%);
        background: sky_brush;
    }

    bg := DayAndNightImage {
        day_image: @image-url("./img/layers/98-background.png");
        night_factor: night_factor;
        night_image: @image-url("./img/layers/98-background-night.png");
        time_of_day: time_of_day;
    }

    Moon {
        moon: moon;
        x: 70px;
        y: -0px;
        opacity: night_factor;
        states [
            night when time_of_day == TimeOfDay.TWILIGHT || time_of_day == TimeOfDay.NIGHT: {
                visible: true;
            }
            day when time_of_day == TimeOfDay.DAY: {
                visible: false;
            }
        ]
    }

    monster_in_house := Monster {
        img_source: monster;
        visible_on_screen: position.visible;
        x: position.x * 1px;
        y: position.y * 1px;
    }

    house := DayAndNightImage {
        day_image: @image-url("./img/layers/0-house.png");
        night_factor: night_factor;
        night_image: @image-url("./img/layers/0-house-night.png");
        time_of_day: time_of_day;
    }

    window := DayAndNightImage {
        day_image: @image-url("./img/layers/1-windows.png");
        night_factor: night_factor;
        night_image: @image-url("./img/layers/1-windows-night.png");
        time_of_day: time_of_day;
    }

    monster_outside := Monster {
        img_source: monster;
        visible_on_screen: position.visible;
        x: position.x * 1px;
        y: position.y * 1px;
    }

    fence := DayAndNightImage {
        day_image: @image-url("./img/layers/2-fence.png");
        night_factor: night_factor;
        night_image: @image-url("./img/layers/2-fence-night.png");
        time_of_day: time_of_day;
    }
}
