export enum WifiState {STARTING, LINK_UP, OK}
export enum TimeOfDay {DAY, TWILIGHT, NIGHT}


export enum MonsterEnv {HOUSE, BALCONY, OUTSIDE, SLEEPING}



export struct MonsterPosition{
    x: int,
    y: int, 
    env: MonsterEnv
}

export global Globals {
    in-out property <int> counter: 0;
    in property <WifiState> wifi_state;

    in property <TimeOfDay> time_of_day;
    in property <image> moon;
    in property <float> night_factor;

    in-out property <string> name;
    in property <MonsterPosition> monster_position;
    in property <bool> monster_visibility;
    in property <brush> sky_brush;

}
