export enum WifiState {STARTING, LINK_UP, OK}
export enum TimeOfDay {DAY, TWILIGHT, NIGHT}


export enum MonsterEnv {HOUSE, BALCONY, OUTSIDE, SLEEPING}



export struct MonsterPosition{
    x: int,
    y: int, 
    env: MonsterEnv
}

export global Globals {
    in-out property <int> counter: 0;
    in property <WifiState> wifi_state;

    in property <TimeOfDay> time_of_day;
    in property <image> moon;
    in property <float> night_factor;

    in-out property <duration> current_time; // duration is a i64, so UNIX timestamps fits.
    in property <MonsterPosition> monster_position;
    in property <bool> monster_visibility;
    in property <brush> sky_brush;
    in property <duration> countdown;
    in property <int> countdown_total_duration;
    pure callback format_countdown(/* now : */duration , /* stops_at: */ duration) -> string;
    pure callback format_time(/* now : */duration) -> string;

}
