import { ScrollView } from "std-widgets.slint";
component Chips inherits Rectangle {
    in property <string> text;
    in property <string> secondary_text;
    in property <string> icon;

    background: #342f31;
    border-radius: 26px;
    clip: false;
    height: 52px;
    chips_icon := Rectangle { /* Vector */
            width: 20px;
        height: 17px;
        x: 16px;
        y: 17.5px;
        // commands: icon;
        // fill-rule: nonzero;
        // stroke-width: 1px;
        // fill: #ff8bcbff;
    }

    chips_text_container := Rectangle { /* Text */
        width: 135px;
        height: 37px;
        x: 44px;
        y: 7.5px;
        Text {
            width: 135px;
            height: 19px;
            x: 0px;
            y: 0px;
            text: text;
            font-family: "Roboto";
            font-size: 15px;
            font-weight: 500;
            horizontal-alignment: left;
            vertical-alignment: bottom;
            letter-spacing: 0.03px;
            overflow: TextOverflow.elide;
            color: #f9eef1ff;
        }

        Text { /* Secondary label */
            width: 135px;
            height: 16px;
            x: 0px;
            y: 21px;
            text: secondary_text;
            font-family: "Roboto";
            font-size: 12px;
            font-weight: 500;
            horizontal-alignment: left;
            vertical-alignment: center;
            letter-spacing: 0.01px;
            color: #cec4c7ff;
        }
    }
}

export  component DataView inherits Rectangle {
    in property <int> screen_size;
    height: screen_size * 1px;
    width: screen_size * 1px;
    background: #f5f5f5ff;
    // in property <int> height: 225px;
    // height: 225px;
    id_3-2685 := Rectangle { /* Tile Layout / Canonical */
        // width: 225px;
        // height: 225px;
        background: #000000ff;
        border-radius: parent.height;
        // clip: true;

        ScrollView {
            VerticalLayout {
                alignment: LayoutAlignment.space-around;
                padding-left: parent.width * 0.06;
                padding-right: parent.width * 0.06;
                spacing: 4px;
                filler := Rectangle {
                    height: screen_size * 0.1664px;
                    width: 100%;
                // background: white;
            }

                id_I3-2686_2250-383707 := Text { /* Primary label */
                width: 100%;
                    text: "Due today";
                    font-family: "Roboto";
                    font-size: 15px;
                    max-height: 20px;
                    font-weight: 500;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    letter-spacing: 0.03px;
                    color: #dadce0ff;
                }

                Rectangle {
                    height: 4px;
                }

                for data in [
                    {
                        text: "Book stay for 3 nights",
                        icon: "",
                        secondary_text: "Secondary label text"
                    },
                    {
                        icon:"",
                        text: "Book Flights",
                        secondary_text: "Secondary label"
                    },
                    {
                        text: "Book stay for 3 nights",
                        icon: "",
                        secondary_text: "Secondary label text"
                    },
                    {
                        icon:"",
                        text: "Book Flights",
                        secondary_text: "Secondary label"
                    },
                    {
                        text: "Book stay for 3 nights",
                        icon: "",
                        secondary_text: "Secondary label text"
                    },
                    {
                        icon:"",
                        text: "Book Flights",
                        secondary_text: "Secondary label"
                    }
                ]: Chips {
                    text: data.text;
                    icon: data.icon;
                    secondary_text: data.secondary_text;
                }

                Rectangle {
                    height: 2 * 52px;
                }
            }

            animate viewport-y {
                easing: ease-out-expo;
                duration: 100ms;
            }
            scrolled() => {
                debug("viewport-y: ", self.viewport-y);
            }
        }
    }
}
