import { HorizontalBox, VerticalBox, Button, Spinner } from "std-widgets.slint";
import "assets/editundo.ttf";

import { Globals, WifiState } from "common.slint";
import { World , Monster} from "background.slint";
export { Globals }

export component Recipe inherits Window {
    default-font-family: "Edit Undo BRK";
    always-on-top: false;
    height: 240px;
    width: 240px;

    world := World {
        monster: @image-url("img/anims/c-1-open.jpg");
        // monster: @image-url("img/test_charmander.png");
        position: Globals.monster_position;
        time_of_day: Globals.time_of_day;
    }

    VerticalBox {
        HorizontalBox {
            max-height: self.min-height;

            Text {
                font-family: "Edit Undo BRK";
                font-size: 72px;
                horizontal-alignment: TextHorizontalAlignment.center;
                text: Globals.name;
            }
        }
    }

    // monster_outside := Monster {
    //     img_source: @image-url("img/test_charmander.png");
    //     visible_on_screen: Globals.monster_position.visible;
    //     x: Globals.monster_position.x * 1px;
    //     y: Globals.monster_position.y * 1px;
    // }

    Image {
        source: @image-url("img/wifi.png");
        x: parent.height - self.height - 2px;
        y: parent.width - self.width - 2px;
        states [
            not_running when Globals.wifi_state == WifiState.STARTING: {
                colorize: red;
            }
            link_up when Globals.wifi_state == WifiState.LINK-UP: {
                colorize: darkorange;
            }
            ok when Globals.wifi_state == WifiState.OK: {
                colorize: darkblue;
            }
        ]
    }
}
